### ISSUE TITLE
Deployment View cannot be generated in c4plantuml when using workspace inclusion

### ISSUE THREAD

**Issue by plgregoire** [structurizr/export#18]
Hi,

I'm trying to separate my workspace in multiple files but I have encountered an issue with the deployment view generation. I have put together a small example that reproduce the issue.

**parent_workspace.dsl**

```
workspace {

    model {
        softwareSystem = softwareSystem "Software System"{
            database = container "Core Container" "" "Database"
        }
    }
}
```

**workspace.dsl**

```
!include parent_workspace.dsl
workspace {

    model {
        !ref softwareSystem {
            service = container "service"
        }
        service -> database "Reads from"


        deploymentEnvironment "OnPremise" {
            deploymentNode "Database Server" {
                containerInstance database
            }

            deploymentNode "Other server"{
                containerInstance service
            }
        }
    }
    
    views {
        deployment * OnPremise "OnPremise"  {
            include *
        }
    }
}
```
The generation will produce this error message

```
Exporting workspace from workspace.dsl
 - loading workspace from DSL
 - using C4PlantUMLExporter
java.lang.NullPointerException: Cannot invoke "com.structurizr.model.Relationship.getTags()" because the return value of "com.structurizr.model.Model.getRelationship(String)" is null
        at com.structurizr.export.plantuml.C4PlantUMLExporter.tagsOf(C4PlantUMLExporter.java:270)
        at com.structurizr.export.plantuml.C4PlantUMLExporter.writeRelationship(C4PlantUMLExporter.java:306)
        at com.structurizr.export.AbstractDiagramExporter.writeRelationships(AbstractDiagramExporter.java:553)
        at com.structurizr.export.AbstractDiagramExporter.export(AbstractDiagramExporter.java:462)
        at com.structurizr.export.AbstractDiagramExporter.export(AbstractDiagramExporter.java:439)
        at com.structurizr.export.AbstractDiagramExporter.export(AbstractDiagramExporter.java:71)
        at com.structurizr.cli.ExportCommand.run(ExportCommand.java:181)
        at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:36)
        at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:81)


```

One last thing to mention. 
If the service and the database were in the same deploymentNode then it would work

**Comment by simonbrowndotje** [comment]
`!include` simply inlines the referenced file, so you have two workspace definitions, which is likely to be causing the problem you’re seeing. See https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#includes for more.

**Comment by plgregoire** [comment]
Oh! So I should have something that looks more like this.

**parent_workspace.dsl**

```
model {
    softwareSystem = softwareSystem "Software System"{
        database = container "Core Container" "" "Database"
    }
}

```

**workspace.dsl**

```
workspace {

    !include parent_workspace.dsl
    
    model {

        !ref softwareSystem {
            service = container "service"
        }
        service -> database "Reads from"


        deploymentEnvironment "OnPremise" {
            deploymentNode "Database Server" {
                containerInstance database
            }

            deploymentNode "Other server"{
                containerInstance service
            }
        }
    }
    
    views {
        deployment * OnPremise "OnPremise"  {
            include *
        }
    }
}
```
It is strange that I had no problem with the other diagram types and only with the deployment. Anyway, It works with this syntax.
Thank you for you help!
